package(default_visibility = ["//visibility:public"])

cc_library(
    name = "base",
    hdrs = ["base.h"]
)

cc_library(
    name = "a",
    hdrs = ["a.h"],
    deps = [":base"],
)

cc_library(
    name = "b",
    hdrs = ["b.h"],
    deps = [":base"],
)

cc_library(
    name = "c",
    hdrs = ["c.h"],
    deps = [":base"],
)